# Write it!

Hc/RailsSpecificActionName:
  Description: |
    Use only specific action names.
  Enabled: false
  ActionNames:
    - create
    - destroy
    - edit
    - index
    - new
    - show
    - update
  Include:
    - app/controllers/**/*.rb
